version: '3'
services:
  fd_analyzer:
    image: fd.harbor.com:8888/public/fd_analyzer:release
    container_name: fd_analyzer
    restart: always
    ports:
      - "17010:17010"
    environment:
      - HOST_IP=${QHYX_HOST_ADDR}
      - CONSULSRV_IP=${QHYX_CONFIG_ADDR}
    tty: true
    volumes:
      - ${QHYX_DATA_DIR:-/opt/qhyx/default_data_dir}/fd_analyzer/log:/home/log/
      - ${QHYX_DATA_DIR:-/opt/qhyx/default_data_dir}/fd_analyzer/data:/home/data/
      - ${QHYX_DATA_DIR:-/opt/qhyx/default_data_dir}/fd_analyzer/config:/home/config/